-- ══════════════════════════════════════════════════════════════════
-- SCORING BASE — Matriz maestra de riesgo 1-10
-- Run in Supabase SQL editor
-- ON CONFLICT DO NOTHING → no sobreescribe ediciones manuales
-- ══════════════════════════════════════════════════════════════════

INSERT INTO asset_master (
  identifier, identifier_type, name, ticker,
  asset_class, risk_score, category, explanation, source, needs_review, updated_at
) VALUES

-- ══════════════════════════════════════════════════════════════════
-- SCORE 1 — MUY CONSERVADOR
-- Volatilidad mínima · Liquidez inmediata · Sin riesgo crédito
-- ══════════════════════════════════════════════════════════════════
('USD_CASH',                   'category', 'USD Cash',                              NULL,   'cash', 1, 'Cash / Efectivo',        'Efectivo en dólares. Volatilidad nula. Liquidez inmediata. Sin riesgo crédito ni mercado.',                                    'Scoring base v1', false, NOW()),
('USD_CHECKING_ACCOUNT',       'category', 'Cuenta corriente USD',                  NULL,   'cash', 1, 'Cash / Efectivo',        'Cuenta corriente en USD en banco custodio regulado. Protegida por FDIC/equivalente hasta límite. Riesgo prácticamente nulo.',   'Scoring base v1', false, NOW()),
('USD_SAVINGS_ACCOUNT',        'category', 'Cuenta de ahorro USD',                  NULL,   'cash', 1, 'Cash / Efectivo',        'Cuenta ahorro USD con acceso inmediato. Rendimiento bajo pero sin riesgo de capital. FDIC u equivalente aplica.',               'Scoring base v1', false, NOW()),
('MONEY_MARKET_USD',           'category', 'Money Market USD',                      NULL,   'cash', 1, 'Cash / Money Market',    'Instrumento de mercado monetario en USD. Alta liquidez, riesgo crediticio mínimo, respaldado por activos de corto plazo.',       'Scoring base v1', false, NOW()),
('TREASURY_BILLS_0_12M',       'category', 'Treasury Bills 0–12 meses',             'SGOV', 'cash', 1, 'Renta fija soberana',    'Letras del Tesoro de EE.UU. con vencimiento hasta 12 meses. Respaldo soberano AAA, sin riesgo de default, mínima duración.',     'Scoring base v1', false, NOW()),
('TREASURY_FLOATING_SHORT',    'category', 'Treasury Floating Rate corto plazo',    'TFLO', 'cash', 1, 'Renta fija soberana',    'Bonos del Tesoro de tasa flotante, corto plazo. Protección total contra suba de tasas. Soberano AAA.',                           'Scoring base v1', false, NOW()),
('MONEY_MARKET_FUND',          'category', 'Fondo Money Market USD',                NULL,   'cash', 1, 'Fondo liquidez',         'Fondo de inversión de mercado monetario en USD. NAV estable $1, liquidez diaria, sin exposición crédito significativa.',        'Scoring base v1', false, NOW()),
('LIQUIDITY_FUND',             'category', 'Fondo de liquidez inmediata',           NULL,   'cash', 1, 'Fondo liquidez',         'Fondo con objetivo de preservar capital y ofrecer acceso inmediato al dinero. Invierte en instrumentos <30 días.',              'Scoring base v1', false, NOW()),
('SOVEREIGN_BILLS_SHORT',      'category', 'Letras soberanas corto plazo',          NULL,   'cash', 1, 'Renta fija soberana',    'Letras emitidas por gobiernos soberanos de alta calidad crediticia (AA+ o superior), vencimiento <12 meses.',                   'Scoring base v1', false, NOW()),
('REPO_COLLATERALIZED',        'category', 'Repo colateralizado (overnight/7 días)','NULL', 'cash', 1, 'Repo / Colateral',       'Operación de recompra colateralizada con bonos soberanos. Uso habitual para gestión de liquidez. Riesgo mínimo.',              'Scoring base v1', false, NOW()),

-- ══════════════════════════════════════════════════════════════════
-- SCORE 2 — CONSERVADOR BAJO
-- Bajo riesgo crédito · Baja volatilidad · Duración corta
-- ══════════════════════════════════════════════════════════════════
('TREASURY_1_3Y',              'category', 'Treasury Notes 1–3 años',               'SHY',  'fixed_income_ig', 2, 'Renta fija soberana EE.UU.',       'Bonos del Tesoro de EE.UU. con vencimiento 1-3 años. Soberano AAA, duración baja, ligero riesgo de tasa.',                        'Scoring base v1', false, NOW()),
('SOVEREIGN_IG_SHORT',         'category', 'Bonos soberanos IG corto plazo',        NULL,   'fixed_income_ig', 2, 'Renta fija soberana IG',            'Deuda soberana de países investment grade (AA/A) con vencimiento <3 años. Bajo riesgo crédito y duración.',                     'Scoring base v1', false, NOW()),
('CORPORATE_IG_AAA_AA_SHORT',  'category', 'Corporativos IG AAA/AA corto plazo',    NULL,   'fixed_income_ig', 2, 'Renta fija corporativa IG',         'Bonos corporativos con calificación AAA o AA, vencimiento <3 años. Emisores de primera línea. Riesgo spread muy bajo.',          'Scoring base v1', false, NOW()),
('ULTRA_SHORT_BOND_FUND',      'category', 'Fondo renta fija ultra short',          'JPST', 'fixed_income_ig', 2, 'Fondo RF corto plazo',              'Fondo de bonos de muy corta duración (<1 año). Busca rendimiento mayor a money market con riesgo marginal adicional.',           'Scoring base v1', false, NOW()),
('MUNI_IG',                    'category', 'Municipal Bonds Investment Grade',      'MUB',  'fixed_income_ig', 2, 'Renta fija municipal EE.UU.',       'Bonos municipales de EE.UU. con grado de inversión. Beneficio fiscal en EE.UU., históricamente bajo default.',                 'Scoring base v1', false, NOW()),
('CD_IG',                      'category', 'Certificados de depósito IG',           NULL,   'fixed_income_ig', 2, 'Instrumento bancario IG',           'Certificados de depósito emitidos por bancos investment grade. Rendimiento predecible, bajo riesgo crédito.',                 'Scoring base v1', false, NOW()),
('GOVT_BOND_SHORT_FUND',       'category', 'Fondo government bonds corto plazo',    'VGSH', 'fixed_income_ig', 2, 'Fondo RF soberana corta',           'Fondo indexado a bonos gubernamentales de alta calidad, vencimiento <3 años. Bajo costo, soberano, baja duración.',              'Scoring base v1', false, NOW()),
('MULTILATERAL_IG_BONDS',      'category', 'Bonos multilaterales investment grade', NULL,   'fixed_income_ig', 2, 'Renta fija multilateral',           'Deuda emitida por organismos multilaterales (BID, Banco Mundial, IFC). Calificación AAA, amplia aceptación institucional.',     'Scoring base v1', false, NOW()),

-- ══════════════════════════════════════════════════════════════════
-- SCORE 3 — CONSERVADOR
-- Bajo/moderado · Sensibilidad tasas · Volatilidad controlada
-- ══════════════════════════════════════════════════════════════════
('TREASURY_3_7Y',              'category', 'Treasury Notes 3–7 años',               'IEI',  'fixed_income_ig', 3, 'Renta fija soberana EE.UU.',       'Notas del Tesoro de EE.UU. con vencimiento 3-7 años. Mayor duración implica mayor sensibilidad a variaciones de tasa.',         'Scoring base v1', false, NOW()),
('SOVEREIGN_IG_LONG',          'category', 'Bonos soberanos IG largo plazo',        'IGOV', 'fixed_income_ig', 3, 'Renta fija soberana IG',            'Deuda soberana de países IG con vencimientos >7 años. Mayor duración, pero alta calidad crediticia. Riesgo tasa relevante.',    'Scoring base v1', false, NOW()),
('CORPORATE_IG_A_BBB',         'category', 'Corporativos IG A/BBB',                 'LQD',  'fixed_income_ig', 3, 'Renta fija corporativa IG',         'Bonos corporativos con calificación A o BBB (frontera IG). Mayor spread sobre soberano, riesgo crédito moderado.',              'Scoring base v1', false, NOW()),
('IG_BOND_FUND',               'category', 'Fondo renta fija investment grade',     'BND',  'fixed_income_ig', 3, 'Fondo RF IG',                       'Fondo diversificado de bonos investment grade. Combina duración media con calidad crediticia sólida.',                          'Scoring base v1', false, NOW()),
('URUGUAY_SOVEREIGN_USD',      'category', 'Uruguay Sovereign Bonds USD',           NULL,   'fixed_income_ig', 3, 'Renta fija soberana LatAm',         'Bonos soberanos de Uruguay denominados en USD. BBB-/investment grade, bajo en el espectro IG. Riesgo país bajo para LatAm.',   'Scoring base v1', false, NOW()),
('GLOBAL_AGGREGATE_FUND',      'category', 'Global aggregate bond fund',            'AGG',  'fixed_income_ig', 3, 'Fondo RF global',                   'Fondo de bonos globales IG (gobierno + corporativo + titulizado). Alta diversificación, duración media, riesgo moneda cubierto.','Scoring base v1', false, NOW()),
('PREFERRED_IG',               'category', 'Preferred shares investment grade',     'PFF',  'fixed_income_ig', 3, 'Acciones preferentes IG',           'Acciones preferentes de empresas IG. Dividendo fijo, subordinadas a deuda pero con cupón estable. Mayor riesgo que bono sénior.','Scoring base v1', false, NOW()),
('MBS_IG',                     'category', 'Mortgage-backed securities IG (agency)','MBB',  'fixed_income_ig', 3, 'Renta fija titulizada',             'Bonos respaldados por hipotecas de agencias (Fannie/Freddie/Ginnie). IG, bajo riesgo crédito, con riesgo prepago.',             'Scoring base v1', false, NOW()),
('BALANCED_CONSERVATIVE_FUND', 'category', 'Fondo balanceado conservador',          NULL,   'fixed_income_ig', 3, 'Fondo multi-activo conservador',    'Fondo con asignación típica 70-80% renta fija / 20-30% renta variable. Objetivo preservación de capital con rentabilidad.',     'Scoring base v1', false, NOW()),
('SHORT_DURATION_BOND',        'category', 'Short duration bond fund',              'BSV',  'fixed_income_ig', 3, 'Fondo RF corta duración',           'Fondo de bonos de duración corta a media (2-4 años). Menor sensibilidad a tasas que aggregate estándar.',                      'Scoring base v1', false, NOW()),

-- ══════════════════════════════════════════════════════════════════
-- SCORE 4 — MODERADO BAJO
-- Exposición equity moderada · Foco income/dividendos
-- ══════════════════════════════════════════════════════════════════
('DIVIDEND_ARISTOCRATS',       'category', 'Dividend Aristocrats',                  'NOBL', 'equity_defensive', 4, 'Equity defensivo dividendos',      'Acciones con 25+ años consecutivos de crecimiento de dividendos. Alta calidad, bajo beta, modelo de negocio estable.',          'Scoring base v1', false, NOW()),
('UTILITIES_EQUITY',           'category', 'Utilities equity',                      'XLU',  'equity_defensive', 4, 'Equity defensivo — Utilities',      'Sector eléctrico/agua/gas. Regulado, flujo de caja predecible, dividendos altos. Bajo beta. Sensible a tasas.',               'Scoring base v1', false, NOW()),
('CONSUMER_STAPLES_EQUITY',    'category', 'Consumer Staples equity',               'XLP',  'equity_defensive', 4, 'Equity defensivo — Consumo básico', 'Empresas de consumo esencial (alimentación, bebidas, higiene). Resiliente en recesiones. Dividendos estables. Beta ~0.6.',      'Scoring base v1', false, NOW()),
('LOW_VOL_ETF',                'category', 'Low volatility equity ETF',             'SPLV', 'equity_defensive', 4, 'Equity baja volatilidad',           'ETF que selecciona las acciones de menor volatilidad del S&P 500. Menor drawdown en caídas, menor retorno en alzas.',          'Scoring base v1', false, NOW()),
('COVERED_CALL_ETF',           'category', 'Covered call / buy-write ETF',          'XYLD', 'equity_defensive', 4, 'Equity income — Opciones cubiertas','ETF que vende opciones call sobre su cartera. Genera ingreso por prima, limita upside. Perfil income + baja vol relativa.',     'Scoring base v1', false, NOW()),
('GOLD_ETF',                   'category', 'Gold ETF',                              'GLD',  'equity_defensive', 4, 'Commodity — Oro',                   'Exposición al precio del oro físico. Activo refugio, cobertura inflación y eventos tail risk. Correlación baja con equity.',   'Scoring base v1', false, NOW()),
('REIT_DEFENSIVE',             'category', 'REITs defensivos',                      'VNQ',  'equity_defensive', 4, 'Real estate defensivo',             'REITs de sectores defensivos (salud, industrial, residencial). Flujo de caja estable, obligación de distribución del 90%.',    'Scoring base v1', false, NOW()),
('INFRASTRUCTURE_FUND',        'category', 'Infrastructure equity fund',            'IGF',  'equity_defensive', 4, 'Infraestructura — Equity',          'Acciones de empresas de infraestructura (peajes, aeropuertos, utilities). Flujos regulados, largo plazo, bajo ciclo.',        'Scoring base v1', false, NOW()),
('CONVERTIBLE_IG',             'category', 'Convertible bonds investment grade',    'CWB',  'fixed_income_ig',  4, 'Bono convertible IG',               'Bono con opción a convertir en acciones. Protección downside (bono) + potencial upside (equity). Emisores IG.',              'Scoring base v1', false, NOW()),
('BALANCED_CONSERVATIVE_PORT', 'category', 'Cartera balanceada conservadora',       NULL,   'equity_defensive', 4, 'Multi-activo conservador',          'Asignación típica 60% RF / 40% RV o similar. Perfil mixto orientado a preservación con algo de crecimiento.',               'Scoring base v1', false, NOW()),
('INCOME_FUND',                'category', 'Income fund diversificado',             NULL,   'equity_defensive', 4, 'Fondo income multi-activo',         'Fondo orientado a generación de ingresos. Combina dividendos, bonos HY moderado, preferentes. Retorno estable.',              'Scoring base v1', false, NOW()),
('MULTI_ASSET_CONSERVATIVE',   'category', 'Multi-asset conservative fund',         NULL,   'equity_defensive', 4, 'Fondo multi-activo moderado-bajo',  'Fondo con asignación dinámica entre clases de activo, sesgo conservador. Gestión activa de riesgo.',                        'Scoring base v1', false, NOW()),

-- ══════════════════════════════════════════════════════════════════
-- SCORE 5 — MODERADO
-- Riesgo equity estándar · Alta diversificación · Volatilidad moderada
-- ══════════════════════════════════════════════════════════════════
('SP500_ETF',                  'category', 'S&P 500 ETF',                           'SPY',  'equity_diversified', 5, 'Equity USA broad market',          'ETF que replica el S&P 500. 500 empresas de mayor capitalización de EE.UU. Benchmark estándar renta variable global.',         'Scoring base v1', false, NOW()),
('MSCI_WORLD_ETF',             'category', 'MSCI World ETF',                        'URTH', 'equity_diversified', 5, 'Equity mercados desarrollados',    'ETF que replica el MSCI World (1600+ empresas de mercados desarrollados). Máxima diversificación geográfica en equity.',       'Scoring base v1', false, NOW()),
('DEVELOPED_MARKETS_EQUITY',   'category', 'Developed markets equity ex-US',        'EFA',  'equity_diversified', 5, 'Equity mercados desarrollados',    'Acciones de mercados desarrollados excluyendo EE.UU. (Europa, Japón, Australasia). Diversificación regional.',               'Scoring base v1', false, NOW()),
('BROAD_MARKET_ETF',           'category', 'Broad market US equity ETF',            'VTI',  'equity_diversified', 5, 'Equity USA total market',          'ETF de mercado total USA (large + mid + small caps). Mayor diversificación que S&P 500, incluye todo el mercado.',            'Scoring base v1', false, NOW()),
('GLOBAL_DIV_EQUITY_FUND',     'category', 'Global diversified equity fund',        NULL,   'equity_diversified', 5, 'Fondo equity global diversificado','Fondo de acciones globales diversificado geográfica y sectorialmente. Gestión activa o pasiva, benchmark MSCI ACWI.',        'Scoring base v1', false, NOW()),
('BALANCED_MODERATE',          'category', 'Cartera balanceada moderada (60/40)',    NULL,   'equity_diversified', 5, 'Multi-activo moderado (60/40)',     'Cartera clásica 60% renta variable / 40% renta fija. Benchmark de referencia para inversores moderados.',                   'Scoring base v1', false, NOW()),
('BLEND_EQUITY_FUND',          'category', 'Blend equity fund (large cap)',          NULL,   'equity_diversified', 5, 'Equity blend large cap',           'Fondo de acciones blend (mezcla value y growth) de gran capitalización. Exposición market-weight diversificada.',             'Scoring base v1', false, NOW()),
('LARGE_CAP_BLEND',            'category', 'Large Cap Blend',                       'IVV',  'equity_diversified', 5, 'Equity large cap blend',           'Acciones de gran capitalización, estilo blend. Sector relativamente diversificado, menos concentrado que growth puro.',       'Scoring base v1', false, NOW()),
('CORE_ALLOCATION_FUND',       'category', 'Core allocation fund',                  NULL,   'equity_diversified', 5, 'Fondo asignación núcleo',           'Fondo de asignación táctica con posición core en equity y RF. Busca equilibrar riesgo-retorno de largo plazo.',              'Scoring base v1', false, NOW()),
('ESG_DIVERSIFIED_FUND',       'category', 'ESG diversified equity fund',           'ESGV', 'equity_diversified', 5, 'Equity ESG diversificado',         'Fondo de renta variable con criterios ESG. Perfil de riesgo similar a broad market, excluyendo sectores controversiales.',    'Scoring base v1', false, NOW()),
('CORPORATE_BBB',              'category', 'Corporate bonds BBB',                   'VCSH', 'fixed_income_ig',  5, 'Renta fija corporativa BBB',        'Bonos corporativos con calificación BBB (grado de inversión mínimo). Mayor spread y riesgo crédito que A/AA.',               'Scoring base v1', false, NOW()),
('REIT_DIVERSIFIED',           'category', 'REIT equity diversificado',             'VNQ',  'real_estate',      5, 'Real estate diversificado',         'REIT con exposición diversificada (comercial, residencial, industrial, salud). Distribución regular, volatilidad media.',     'Scoring base v1', false, NOW()),
('EQUITY_INCOME_DIVERSIFIED',  'category', 'Equity income diversificado',           'DVY',  'equity_diversified', 5, 'Equity income diversificado',      'Fondo o ETF que combina dividendos altos con diversificación sectorial amplia. Income + apreciación de capital.',            'Scoring base v1', false, NOW()),

-- ══════════════════════════════════════════════════════════════════
-- SCORE 6 — MODERADO ALTO
-- Volatilidad elevada · Mayor riesgo crédito · Sensibilidad económica
-- ══════════════════════════════════════════════════════════════════
('HIGH_YIELD_BONDS',           'category', 'High Yield Bonds',                      'HYG',  'fixed_income_hy',  6, 'Renta fija high yield',             'Bonos corporativos sub-investment grade (BB y menores). Mayor rendimiento, mayor riesgo de default, correlación con equity.',  'Scoring base v1', false, NOW()),
('SMALL_CAP_BLEND',            'category', 'Small Cap Blend equity',                'IWM',  'equity_diversified', 6, 'Equity small caps',                'Acciones de pequeña capitalización (Russell 2000). Mayor crecimiento potencial pero mayor volatilidad y menor liquidez.',     'Scoring base v1', false, NOW()),
('MID_CAP_EQUITY',             'category', 'Mid Cap equity',                        'IJH',  'equity_diversified', 6, 'Equity mid caps',                  'Acciones de capitalización media. Combinación de potencial crecimiento (small cap) y estabilidad (large cap).',              'Scoring base v1', false, NOW()),
('PREFERRED_HY',               'category', 'Preferred shares high yield',           NULL,   'fixed_income_hy',  6, 'Acciones preferentes HY',           'Preferentes de emisores sub-investment grade. Alto dividendo, baja prioridad en quiebra, volatilidad elevada.',              'Scoring base v1', false, NOW()),
('FRONTIER_BONDS',             'category', 'Frontier market bonds',                 NULL,   'fixed_income_hy',  6, 'Renta fija frontier markets',       'Bonos de países frontier (menor desarrollo que EM). Mayor rendimiento, mayor riesgo político/cambiario/liquidez.',           'Scoring base v1', false, NOW()),
('REIT_AGGRESSIVE',            'category', 'REITs agresivos / especializados',      NULL,   'real_estate',      6, 'Real estate agresivo',              'REITs de sectores más volátiles (hoteles, oficinas, retail). Mayor exposición al ciclo económico.',                         'Scoring base v1', false, NOW()),
('SECTOR_DIVERSIFIED_FUND',    'category', 'Sector diversified fund',               NULL,   'equity_diversified', 6, 'Fondo sectorial diversificado',    'Fondo que combina varios sectores con overweight en segmentos cíclicos. Mayor beta que broad market.',                     'Scoring base v1', false, NOW()),
('MULTI_ASSET_AGGRESSIVE',     'category', 'Multi-asset aggressive',                NULL,   'equity_diversified', 6, 'Fondo multi-activo agresivo',      'Asignación dinámica con sesgo agresivo: overweight equity, HY, EM. Mayor retorno esperado y mayor volatilidad.',           'Scoring base v1', false, NOW()),
('BANK_SUBORDINATED_DEBT',     'category', 'Bank subordinated debt / AT1',          NULL,   'fixed_income_hy',  6, 'Deuda subordinada bancaria',        'Bonos subordinados y CoCos de bancos. Absorben pérdidas antes que deuda senior. Cupones altos, riesgo regulatorio.',        'Scoring base v1', false, NOW()),
('CLO_FUND',                   'category', 'CLO / Loan fund',                       NULL,   'fixed_income_hy',  6, 'CLO / Préstamos sindicados',        'Obligaciones colateralizadas por préstamos corporativos. Estructura compleja, tasa flotante, riesgo crédito elevado.',       'Scoring base v1', false, NOW()),
('FLOATING_RATE_HY',           'category', 'Floating rate high yield',              'BKLN', 'fixed_income_hy',  6, 'Renta fija HY tasa flotante',       'Préstamos bancarios sindicados de tasa flotante a emisores sub-IG. Protección tasa + riesgo crédito elevado.',              'Scoring base v1', false, NOW()),
('STRUCTURED_INCOME',          'category', 'Structured income products',            NULL,   'fixed_income_hy',  6, 'Productos estructurados income',    'Notas estructuradas con capital protegido o condicionado. Perfil asimétrico. Riesgo emisor + riesgo estructura.',           'Scoring base v1', false, NOW()),

-- ══════════════════════════════════════════════════════════════════
-- SCORE 7 — AGRESIVO
-- Alta volatilidad · Concentración sectorial · Sensibilidad macro
-- ══════════════════════════════════════════════════════════════════
('NASDAQ_100_QQQ',             'category', 'Nasdaq 100 / QQQ',                      'QQQ',  'equity_growth',    7, 'Equity growth — Tecnología USA',    'ETF que replica el Nasdaq 100 (100 mayores empresas no financieras Nasdaq). Alta concentración en tech. P/E elevado.',       'Scoring base v1', false, NOW()),
('GROWTH_EQUITY_FUND',         'category', 'Growth equity fund',                    'IWF',  'equity_growth',    7, 'Equity growth diversificado',       'Fondo de acciones growth (alto crecimiento estimado de earnings). Mayor P/E, mayor sensibilidad a tasas y ciclo.',           'Scoring base v1', false, NOW()),
('TECHNOLOGY_FUND',            'category', 'Technology sector fund',                'XLK',  'equity_growth',    7, 'Equity — Tecnología',               'Fondo sectorial tecnológico. Alto potencial de crecimiento, alta volatilidad, concentración en pocas posiciones grandes.',    'Scoring base v1', false, NOW()),
('BIOTECH_FUND',               'category', 'Biotech / Healthcare growth fund',      'XBI',  'equity_growth',    7, 'Equity — Biotech',                  'Sector biotecnológico. Altos retornos potenciales por aprobaciones FDA. Riesgo binario muy elevado por ensayos clínicos.',   'Scoring base v1', false, NOW()),
('COMMODITIES_BROAD',          'category', 'Commodities broad basket',              'DJP',  'commodity',        7, 'Commodities diversificados',        'Exposición a cesta diversificada de materias primas (energía, metales, agrícolas). Alta volatilidad, cobertura inflación.',  'Scoring base v1', false, NOW()),
('EMERGING_MARKETS_DEBT',      'category', 'Emerging Markets Debt (EM Bonds)',      'EMB',  'fixed_income_hy',  7, 'Renta fija mercados emergentes',    'Bonos soberanos y corporativos de mercados emergentes en USD. Mayor spread, riesgo político, cambiario y liquidez.',         'Scoring base v1', false, NOW()),
('CHINA_EQUITY_FUND',          'category', 'China equity fund',                     'MCHI', 'equity_emerging',  7, 'Equity China',                      'Acciones chinas (A-shares, H-shares, ADRs). Riesgo regulatorio específico China, geopolítico, opacidad contable.',          'Scoring base v1', false, NOW()),
('LATAM_EQUITY',               'category', 'Latin America equity',                  'ILF',  'equity_emerging',  7, 'Equity América Latina',             'Acciones de mercados latinoamericanos (Brasil, México, Chile, Colombia). Alta sensibilidad a commodities y tipo de cambio.', 'Scoring base v1', false, NOW()),
('LEVERAGED_BOND',             'category', 'Leveraged bond fund',                   NULL,   'fixed_income_hy',  7, 'Renta fija apalancada',             'Fondo de bonos con uso de apalancamiento para ampliar retornos. Mayor riesgo en caídas, posibles margin calls.',             'Scoring base v1', false, NOW()),
('CONCENTRATED_SECTOR_ETF',    'category', 'Concentrated sector ETF',               NULL,   'equity_growth',    7, 'Equity sectorial concentrado',      'ETF con foco en un sector específico (semiconductores, finanzas, energía). Alta concentración, sin diversificación.',        'Scoring base v1', false, NOW()),
('MOMENTUM_FUND',              'category', 'Momentum equity fund',                  'MTUM', 'equity_growth',    7, 'Equity factor — Momentum',          'Fondo que sobrepondera acciones con mejor rendimiento reciente. Factor momentum amplifica ciclos, alta rotación.',           'Scoring base v1', false, NOW()),
('INNOVATION_FUND',            'category', 'Innovation / Disruptive fund',          'ARKK', 'equity_growth',    7, 'Equity temático innovación',        'Fondo de empresas disruptivas (genómica, fintech, robótica). Alta concentración, alto P/E, drawdowns históricos >50%.',     'Scoring base v1', false, NOW()),
('CYBERSECURITY_FUND',         'category', 'Cybersecurity thematic fund',           'CIBR', 'equity_growth',    7, 'Equity temático — Ciberseguridad',  'Empresas de ciberseguridad. Sector creciente, concentrado en pocas posiciones, alta volatilidad sectorial.',                'Scoring base v1', false, NOW()),
('AI_THEMATIC_FUND',           'category', 'AI / Artificial Intelligence fund',     NULL,   'equity_growth',    7, 'Equity temático — Inteligencia Artificial', 'Fondo temático de inteligencia artificial. Alta expectativa de crecimiento, valoraciones elevadas, concentración tech.', 'Scoring base v1', false, NOW()),

-- ══════════════════════════════════════════════════════════════════
-- SCORE 8 — MUY AGRESIVO
-- Volatilidad muy alta · Drawdowns importantes · Concentración
-- ══════════════════════════════════════════════════════════════════
('EM_EQUITY',                  'category', 'Emerging Markets equity broad',         'EEM',  'equity_emerging',  8, 'Equity mercados emergentes',        'Acciones de mercados emergentes amplios (China, India, Brasil, Taiwán, Corea). Mayor potencial, mayor volatilidad que DM.',   'Scoring base v1', false, NOW()),
('SINGLE_STOCK_LARGE_GROWTH',  'category', 'Single stock large cap growth',         NULL,   'equity_growth',    8, 'Acción individual — Large cap growth', 'Posición en una sola acción de alta capitalización con sesgo growth. Sin diversificación, riesgo idiosincrático elevado.', 'Scoring base v1', false, NOW()),
('SINGLE_STOCK_CYCLICAL',      'category', 'Single stock cíclico',                  NULL,   'equity_growth',    8, 'Acción individual — Cíclico',       'Posición concentrada en una acción cíclica (energía, materiales, industriales). Alta volatilidad ligada al ciclo económico.','Scoring base v1', false, NOW()),
('FRONTIER_MARKETS_EQUITY',    'category', 'Frontier Markets equity',               'FM',   'equity_emerging',  8, 'Equity frontier markets',           'Acciones de mercados frontera (Vietnam, Nigeria, Kazajistán). Menor liquidez, mayor riesgo país, alta volatilidad.',         'Scoring base v1', false, NOW()),
('COMMODITY_PRODUCERS',        'category', 'Commodity producers equity',            'XME',  'equity_emerging',  8, 'Equity productores de commodities','Acciones de empresas productoras de materias primas. Apalancamiento operativo sobre precio commodity, alta volatilidad.',   'Scoring base v1', false, NOW()),
('OIL_GAS_EXPLORATION',        'category', 'Oil & Gas exploration equity',          'XOP',  'equity_growth',    8, 'Equity — Exploración O&G',          'Empresas de exploración petróleo y gas. Riesgo geológico + precio commodity + geopolítico. Drawdowns >50% frecuentes.',    'Scoring base v1', false, NOW()),
('JUNIOR_MINERS',              'category', 'Junior miners equity',                  NULL,   'equity_emerging',  8, 'Equity — Minería junior',           'Pequeñas empresas mineras en fase exploración/desarrollo. Riesgo extremo de proyecto, baja liquidez, alta volatilidad.',    'Scoring base v1', false, NOW()),
('VENTURE_GROWTH_FUND',        'category', 'Venture / growth equity fund',          NULL,   'equity_growth',    8, 'Private equity — Venture growth',   'Fondo de equity en empresas de crecimiento tardío pre-IPO. Iliquidez, valoraciones agresivas, horizonte 5-10 años.',         'Scoring base v1', false, NOW()),
('PE_GROWTH',                  'category', 'Private equity growth',                 NULL,   'equity_growth',    8, 'Private equity growth',             'Inversión en private equity crecimiento. Ilíquido, largo plazo, high fees. Retornos potenciales altos si el exit es exitoso.','Scoring base v1', false, NOW()),
('CONCENTRATED_ACTIVE_EQUITY', 'category', 'Concentrated active equity fund',       NULL,   'equity_growth',    8, 'Fondo equity concentrado activo',   'Fondo de gestión activa con 10-20 posiciones. Tracking error muy alto, riesgo gestor, potencial alpha o pérdida.',           'Scoring base v1', false, NOW()),
('LEVERAGED_COMMODITIES',      'category', 'Leveraged commodity fund',              NULL,   'commodity',        8, 'Commodities apalancados',           'Exposición apalancada a materias primas. Amplificación volatilidad, decay por roll de futuros en mercados contango.',        'Scoring base v1', false, NOW()),
('HIGH_BETA_EQUITY',           'category', 'High beta equity',                      NULL,   'equity_growth',    8, 'Equity alto beta',                  'Acciones con beta >1.5 respecto al mercado. Amplifican tanto subidas como caídas del mercado.',                            'Scoring base v1', false, NOW()),
('SPECULATIVE_THEMATIC',       'category', 'Speculative thematic fund',             NULL,   'equity_growth',    8, 'Fondo temático especulativo',       'Fondo temático en sectores especulativos (cannabis, NFTs, metaverso). Narrativa fuerte, fundamentales débiles.',             'Scoring base v1', false, NOW()),

-- ══════════════════════════════════════════════════════════════════
-- SCORE 9 — ESPECULATIVO
-- Extremadamente volátil · Alta pérdida potencial · Movimientos bruscos
-- ══════════════════════════════════════════════════════════════════
('BITCOIN',                    'category', 'Bitcoin',                               'BTC',  'crypto',           9, 'Crypto — Bitcoin',                  'Criptomoneda de mayor capitalización. Volatilidad anualizada >60%. Drawdowns de 80%+ registrados. Sin flujo de caja subyacente.','Scoring base v1', false, NOW()),
('ETHEREUM',                   'category', 'Ethereum',                              'ETH',  'crypto',           9, 'Crypto — Ethereum',                 'Segunda criptomoneda por capitalización. Plataforma de contratos inteligentes. Alta volatilidad, correlación con BTC.',        'Scoring base v1', false, NOW()),
('DISTRESSED_DEBT',            'category', 'Distressed debt',                       NULL,   'fixed_income_hy',  9, 'Deuda distressed',                  'Bonos de empresas en dificultades financieras o en default. Requiere expertise legal. Retornos potenciales muy altos o cero.','Scoring base v1', false, NOW()),
('LEVERAGED_STRUCTURED',       'category', 'Leveraged structured products',         NULL,   'other',            9, 'Productos estructurados apalancados','Notas y certificados con apalancamiento incorporado. Pérdida de capital posible, riesgo emisor elevado.',                   'Scoring base v1', false, NOW()),
('NON_IG_DISTRESSED',          'category', 'Non-IG distressed bonds',               NULL,   'fixed_income_hy',  9, 'Bonos CCC / CC / distressed',       'Bonos corporativos con calificación CCC o inferior. Alta tasa de default esperada, recuperación incierta.',                'Scoring base v1', false, NOW()),
('VOLATILITY_TRADING',         'category', 'Volatility trading products',           'VXX', 'other',             9, 'Trading de volatilidad',            'ETPs que replican VIX o estrategias de volatilidad. Decay estructural severo, solo para trading corto plazo.',               'Scoring base v1', false, NOW()),
('HEDGE_FUND_SPECULATIVE',     'category', 'Hedge fund — Estrategias especulativas',NULL,   'other',            9, 'Hedge fund especulativo',           'Fondos de cobertura con estrategias de alta convicción (long/short concentrado, event-driven, macro). Alta varianza resultados.','Scoring base v1', false, NOW()),
('LEVERAGED_DERIVATIVES',      'category', 'Leveraged derivatives / opciones',      NULL,   'other',            9, 'Derivados apalancados',             'Opciones, futuros y otros derivados con apalancamiento implícito. Puede perder el 100% del capital invertido en posiciones largas.','Scoring base v1', false, NOW()),
('CONCENTRATED_CRYPTO',        'category', 'Concentrated crypto portfolio',         NULL,   'crypto',           9, 'Crypto concentrado (2-5 monedas)',  'Cartera de pocas criptomonedas seleccionadas. Mayor concentración que BTC/ETH solos, volatilidad extrema.',                 'Scoring base v1', false, NOW()),
('SPAC_SPECULATIVE',           'category', 'SPAC especulativo',                     NULL,   'other',            9, 'SPAC especulativo',                 'Special Purpose Acquisition Company. Caja sin activo real hasta el deal. Post-merger altamente especulativo y volátil.',     'Scoring base v1', false, NOW()),
('DEEP_TECH_VENTURE',          'category', 'Deep tech venture fund',                NULL,   'other',            9, 'Venture — Deep tech',               'Fondo de capital riesgo en tecnología profunda (quantum, biotech early stage). Ilíquido, horizonte 10+ años, alto riesgo ejecución.','Scoring base v1', false, NOW()),

-- ══════════════════════════════════════════════════════════════════
-- SCORE 10 — MÁXIMO RIESGO
-- Riesgo extremo · Pérdida total posible · Liquidez reducida
-- ══════════════════════════════════════════════════════════════════
('ALTCOINS_SPECULATIVE',       'category', 'Altcoins especulativas (meme coins)',   NULL,   'crypto',           10, 'Crypto — Altcoins especulativas',  'Criptomonedas de baja capitalización con narrativa especulativa. Pérdida total frecuente, manipulación de mercado, liquidez mínima.','Scoring base v1', false, NOW()),
('PENNY_STOCKS',               'category', 'Penny stocks',                          NULL,   'other',            10, 'Acciones especulativas — Penny',   'Acciones de precio muy bajo (<$1), baja capitalización y escasa liquidez. Manipuladas frecuentemente. Riesgo de pérdida total.','Scoring base v1', false, NOW()),
('MICROCAPS_ILLIQUID',         'category', 'Microcaps ilíquidas',                   NULL,   'other',            10, 'Equity microcap ilíquido',         'Acciones de empresas muy pequeñas con volumen de trading mínimo. Imposible salir en mercado adverso. Spread bid/ask enorme.','Scoring base v1', false, NOW()),
('INVERSE_ETF',                'category', 'Inverse ETF (short market)',            'SH',   'other',            10, 'ETF inverso',                      'ETF que replica el inverso del índice. Decay estructural por rebalanceo diario. Pierde valor en mercados laterales o alcistas.','Scoring base v1', false, NOW()),
('LEVERAGED_ETF_2X_3X',        'category', 'Leveraged ETF 2x / 3x',                'TQQQ', 'other',            10, 'ETF apalancado 2x/3x',             'ETF que amplifica 2x o 3x la rentabilidad diaria del índice. Decay diario destruye valor en largo plazo. Solo para day trading.','Scoring base v1', false, NOW()),
('NAKED_OPTIONS',              'category', 'Naked options / opciones desnudas',     NULL,   'other',            10, 'Opciones no cubiertas',             'Venta de opciones sin cobertura del activo subyacente. Pérdida potencial ilimitada en calls, muy alta en puts.',              'Scoring base v1', false, NOW()),
('HIGHLY_LEVERAGED_DERIVATIVES','category','Derivados altamente apalancados',       NULL,   'other',            10, 'Derivados máximo apalancamiento',  'CFDs, futuros con máximo apalancamiento. Margin calls pueden exceder el capital inicial. Riesgo de pérdida superior al 100%.','Scoring base v1', false, NOW()),
('MEME_STOCKS',                'category', 'Meme stocks especulativas',             NULL,   'other',            10, 'Meme stocks',                      'Acciones impulsadas por redes sociales sin fundamentales. GameStop, AMC style. Volatilidad extrema, pump & dump patterns.',    'Scoring base v1', false, NOW()),
('ILLIQUID_PRIVATE',           'category', 'Illiquid private investments',          NULL,   'other',            10, 'Inversión privada ilíquida',        'Inversiones privadas sin mercado secundario. Sin precio de salida, lock-up permanente, riesgo total de pérdida de capital.',   'Scoring base v1', false, NOW()),
('DISTRESSED_MICROCAP_DEBT',   'category', 'Distressed microcap debt',              NULL,   'other',            10, 'Deuda distressed microcap',        'Deuda de empresas micro con alto riesgo de quiebra. Prácticamente sin liquidez. Recuperación en default cercana a cero.',    'Scoring base v1', false, NOW()),
('EXOTIC_STRUCTURED',          'category', 'Exotic structured products',            NULL,   'other',            10, 'Productos estructurados exóticos',  'Notas con payoffs complejos vinculados a eventos poco probables. Opacidad total. Riesgo de pérdida completa del capital.',   'Scoring base v1', false, NOW()),
('BINARY_OPTIONS',             'category', 'Binary options',                        NULL,   'other',            10, 'Opciones binarias',                 'Instrumentos tipo "todo o nada". Extremadamente especulativo. Regulado como apuesta en muchas jurisdicciones. Pérdida total.','Scoring base v1', false, NOW())

ON CONFLICT (identifier) DO NOTHING;

-- Verificación: contar por score
SELECT risk_score, COUNT(*) as total
FROM asset_master
WHERE source = 'Scoring base v1'
GROUP BY risk_score
ORDER BY risk_score;
