/**
 * POST /api/suitability/asset-master/seed
 * Carga la matriz maestra de scoring base (115 entradas, scores 1-10).
 * Usa ON CONFLICT DO NOTHING → no sobreescribe ediciones manuales.
 * Solo admins.
 */
import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import { getSession } from '@/lib/auth'

const SEED_DATA: {
  identifier: string
  identifier_type: string
  name: string
  ticker: string | null
  asset_class: string
  risk_score: number
  category: string
  explanation: string
  source: string
}[] = [
  // ── SCORE 1 — MUY CONSERVADOR ───────────────────────────────────────────────
  { identifier: 'USD_CASH',                   identifier_type: 'category', name: 'USD Cash',                               ticker: null,   asset_class: 'cash',               risk_score: 1,  category: 'Cash / Efectivo',                   explanation: 'Efectivo en dólares. Volatilidad nula. Liquidez inmediata. Sin riesgo crédito ni mercado.',                                     source: 'Scoring base v1' },
  { identifier: 'USD_CHECKING_ACCOUNT',       identifier_type: 'category', name: 'Cuenta corriente USD',                   ticker: null,   asset_class: 'cash',               risk_score: 1,  category: 'Cash / Efectivo',                   explanation: 'Cuenta corriente en USD en banco custodio regulado. Protegida por FDIC/equivalente hasta límite.',                             source: 'Scoring base v1' },
  { identifier: 'USD_SAVINGS_ACCOUNT',        identifier_type: 'category', name: 'Cuenta de ahorro USD',                   ticker: null,   asset_class: 'cash',               risk_score: 1,  category: 'Cash / Efectivo',                   explanation: 'Cuenta ahorro USD con acceso inmediato. Rendimiento bajo pero sin riesgo de capital.',                                         source: 'Scoring base v1' },
  { identifier: 'MONEY_MARKET_USD',           identifier_type: 'category', name: 'Money Market USD',                       ticker: null,   asset_class: 'cash',               risk_score: 1,  category: 'Cash / Money Market',               explanation: 'Instrumento de mercado monetario en USD. Alta liquidez, riesgo crediticio mínimo, respaldado por activos de corto plazo.',       source: 'Scoring base v1' },
  { identifier: 'TREASURY_BILLS_0_12M',       identifier_type: 'category', name: 'Treasury Bills 0–12 meses',              ticker: 'SGOV', asset_class: 'cash',               risk_score: 1,  category: 'Renta fija soberana',               explanation: 'Letras del Tesoro de EE.UU. con vencimiento hasta 12 meses. Respaldo soberano AAA, sin riesgo de default, mínima duración.',     source: 'Scoring base v1' },
  { identifier: 'TREASURY_FLOATING_SHORT',    identifier_type: 'category', name: 'Treasury Floating Rate corto plazo',     ticker: 'TFLO', asset_class: 'cash',               risk_score: 1,  category: 'Renta fija soberana',               explanation: 'Bonos del Tesoro de tasa flotante, corto plazo. Protección total contra suba de tasas. Soberano AAA.',                           source: 'Scoring base v1' },
  { identifier: 'MONEY_MARKET_FUND',          identifier_type: 'category', name: 'Fondo Money Market USD',                 ticker: null,   asset_class: 'cash',               risk_score: 1,  category: 'Fondo liquidez',                    explanation: 'Fondo de inversión de mercado monetario en USD. NAV estable $1, liquidez diaria, sin exposición crédito significativa.',        source: 'Scoring base v1' },
  { identifier: 'LIQUIDITY_FUND',             identifier_type: 'category', name: 'Fondo de liquidez inmediata',            ticker: null,   asset_class: 'cash',               risk_score: 1,  category: 'Fondo liquidez',                    explanation: 'Fondo con objetivo de preservar capital y ofrecer acceso inmediato al dinero. Invierte en instrumentos <30 días.',              source: 'Scoring base v1' },
  { identifier: 'SOVEREIGN_BILLS_SHORT',      identifier_type: 'category', name: 'Letras soberanas corto plazo',           ticker: null,   asset_class: 'cash',               risk_score: 1,  category: 'Renta fija soberana',               explanation: 'Letras emitidas por gobiernos soberanos de alta calidad crediticia (AA+ o superior), vencimiento <12 meses.',                   source: 'Scoring base v1' },
  { identifier: 'REPO_COLLATERALIZED',        identifier_type: 'category', name: 'Repo colateralizado (overnight/7d)',     ticker: null,   asset_class: 'cash',               risk_score: 1,  category: 'Repo / Colateral',                  explanation: 'Operación de recompra colateralizada con bonos soberanos. Uso habitual para gestión de liquidez. Riesgo mínimo.',              source: 'Scoring base v1' },

  // ── SCORE 2 — CONSERVADOR BAJO ──────────────────────────────────────────────
  { identifier: 'TREASURY_1_3Y',              identifier_type: 'category', name: 'Treasury Notes 1–3 años',                ticker: 'SHY',  asset_class: 'fixed_income_ig',    risk_score: 2,  category: 'Renta fija soberana EE.UU.',        explanation: 'Bonos del Tesoro de EE.UU. con vencimiento 1-3 años. Soberano AAA, duración baja, ligero riesgo de tasa.',                        source: 'Scoring base v1' },
  { identifier: 'SOVEREIGN_IG_SHORT',         identifier_type: 'category', name: 'Bonos soberanos IG corto plazo',         ticker: null,   asset_class: 'fixed_income_ig',    risk_score: 2,  category: 'Renta fija soberana IG',            explanation: 'Deuda soberana de países investment grade (AA/A) con vencimiento <3 años. Bajo riesgo crédito y duración.',                     source: 'Scoring base v1' },
  { identifier: 'CORPORATE_IG_AAA_AA_SHORT',  identifier_type: 'category', name: 'Corporativos IG AAA/AA corto plazo',     ticker: null,   asset_class: 'fixed_income_ig',    risk_score: 2,  category: 'Renta fija corporativa IG',         explanation: 'Bonos corporativos con calificación AAA o AA, vencimiento <3 años. Emisores de primera línea. Riesgo spread muy bajo.',          source: 'Scoring base v1' },
  { identifier: 'ULTRA_SHORT_BOND_FUND',      identifier_type: 'category', name: 'Fondo renta fija ultra short',           ticker: 'JPST', asset_class: 'fixed_income_ig',    risk_score: 2,  category: 'Fondo RF corto plazo',              explanation: 'Fondo de bonos de muy corta duración (<1 año). Busca rendimiento mayor a money market con riesgo marginal adicional.',           source: 'Scoring base v1' },
  { identifier: 'MUNI_IG',                    identifier_type: 'category', name: 'Municipal Bonds Investment Grade',       ticker: 'MUB',  asset_class: 'fixed_income_ig',    risk_score: 2,  category: 'Renta fija municipal EE.UU.',       explanation: 'Bonos municipales de EE.UU. con grado de inversión. Beneficio fiscal en EE.UU., históricamente bajo default.',                 source: 'Scoring base v1' },
  { identifier: 'CD_IG',                      identifier_type: 'category', name: 'Certificados de depósito IG',            ticker: null,   asset_class: 'fixed_income_ig',    risk_score: 2,  category: 'Instrumento bancario IG',           explanation: 'Certificados de depósito emitidos por bancos investment grade. Rendimiento predecible, bajo riesgo crédito.',                 source: 'Scoring base v1' },
  { identifier: 'GOVT_BOND_SHORT_FUND',       identifier_type: 'category', name: 'Fondo government bonds corto plazo',     ticker: 'VGSH', asset_class: 'fixed_income_ig',    risk_score: 2,  category: 'Fondo RF soberana corta',           explanation: 'Fondo indexado a bonos gubernamentales de alta calidad, vencimiento <3 años. Bajo costo, soberano, baja duración.',              source: 'Scoring base v1' },
  { identifier: 'MULTILATERAL_IG_BONDS',      identifier_type: 'category', name: 'Bonos multilaterales investment grade',  ticker: null,   asset_class: 'fixed_income_ig',    risk_score: 2,  category: 'Renta fija multilateral',           explanation: 'Deuda emitida por organismos multilaterales (BID, Banco Mundial, IFC). Calificación AAA, amplia aceptación institucional.',     source: 'Scoring base v1' },

  // ── SCORE 3 — CONSERVADOR ───────────────────────────────────────────────────
  { identifier: 'TREASURY_3_7Y',              identifier_type: 'category', name: 'Treasury Notes 3–7 años',                ticker: 'IEI',  asset_class: 'fixed_income_ig',    risk_score: 3,  category: 'Renta fija soberana EE.UU.',        explanation: 'Notas del Tesoro de EE.UU. con vencimiento 3-7 años. Mayor duración implica mayor sensibilidad a variaciones de tasa.',         source: 'Scoring base v1' },
  { identifier: 'SOVEREIGN_IG_LONG',          identifier_type: 'category', name: 'Bonos soberanos IG largo plazo',         ticker: 'IGOV', asset_class: 'fixed_income_ig',    risk_score: 3,  category: 'Renta fija soberana IG',            explanation: 'Deuda soberana de países IG con vencimientos >7 años. Mayor duración, pero alta calidad crediticia. Riesgo tasa relevante.',    source: 'Scoring base v1' },
  { identifier: 'CORPORATE_IG_A_BBB',         identifier_type: 'category', name: 'Corporativos IG A/BBB',                  ticker: 'LQD',  asset_class: 'fixed_income_ig',    risk_score: 3,  category: 'Renta fija corporativa IG',         explanation: 'Bonos corporativos con calificación A o BBB (frontera IG). Mayor spread sobre soberano, riesgo crédito moderado.',              source: 'Scoring base v1' },
  { identifier: 'IG_BOND_FUND',               identifier_type: 'category', name: 'Fondo renta fija investment grade',      ticker: 'BND',  asset_class: 'fixed_income_ig',    risk_score: 3,  category: 'Fondo RF IG',                       explanation: 'Fondo diversificado de bonos investment grade. Combina duración media con calidad crediticia sólida.',                          source: 'Scoring base v1' },
  { identifier: 'URUGUAY_SOVEREIGN_USD',      identifier_type: 'category', name: 'Uruguay Sovereign Bonds USD',            ticker: null,   asset_class: 'fixed_income_ig',    risk_score: 3,  category: 'Renta fija soberana LatAm',         explanation: 'Bonos soberanos de Uruguay denominados en USD. BBB-/investment grade, bajo en el espectro IG. Riesgo país bajo para LatAm.',   source: 'Scoring base v1' },
  { identifier: 'GLOBAL_AGGREGATE_FUND',      identifier_type: 'category', name: 'Global aggregate bond fund',             ticker: 'AGG',  asset_class: 'fixed_income_ig',    risk_score: 3,  category: 'Fondo RF global',                   explanation: 'Fondo de bonos globales IG (gobierno + corporativo + titulizado). Alta diversificación, duración media, riesgo moneda cubierto.', source: 'Scoring base v1' },
  { identifier: 'PREFERRED_IG',               identifier_type: 'category', name: 'Preferred shares investment grade',      ticker: 'PFF',  asset_class: 'fixed_income_ig',    risk_score: 3,  category: 'Acciones preferentes IG',           explanation: 'Acciones preferentes de empresas IG. Dividendo fijo, subordinadas a deuda pero con cupón estable. Mayor riesgo que bono sénior.', source: 'Scoring base v1' },
  { identifier: 'MBS_IG',                     identifier_type: 'category', name: 'Mortgage-backed securities IG (agency)', ticker: 'MBB',  asset_class: 'fixed_income_ig',    risk_score: 3,  category: 'Renta fija titulizada',             explanation: 'Bonos respaldados por hipotecas de agencias (Fannie/Freddie/Ginnie). IG, bajo riesgo crédito, con riesgo prepago.',             source: 'Scoring base v1' },
  { identifier: 'BALANCED_CONSERVATIVE_FUND', identifier_type: 'category', name: 'Fondo balanceado conservador',           ticker: null,   asset_class: 'fixed_income_ig',    risk_score: 3,  category: 'Fondo multi-activo conservador',    explanation: 'Fondo con asignación típica 70-80% renta fija / 20-30% renta variable. Objetivo preservación de capital con rentabilidad.',     source: 'Scoring base v1' },
  { identifier: 'SHORT_DURATION_BOND',        identifier_type: 'category', name: 'Short duration bond fund',               ticker: 'BSV',  asset_class: 'fixed_income_ig',    risk_score: 3,  category: 'Fondo RF corta duración',           explanation: 'Fondo de bonos de duración corta a media (2-4 años). Menor sensibilidad a tasas que aggregate estándar.',                      source: 'Scoring base v1' },

  // ── SCORE 4 — MODERADO BAJO ─────────────────────────────────────────────────
  { identifier: 'DIVIDEND_ARISTOCRATS',       identifier_type: 'category', name: 'Dividend Aristocrats',                   ticker: 'NOBL', asset_class: 'equity_defensive',   risk_score: 4,  category: 'Equity defensivo dividendos',       explanation: 'Acciones con 25+ años consecutivos de crecimiento de dividendos. Alta calidad, bajo beta, modelo de negocio estable.',          source: 'Scoring base v1' },
  { identifier: 'UTILITIES_EQUITY',           identifier_type: 'category', name: 'Utilities equity',                       ticker: 'XLU',  asset_class: 'equity_defensive',   risk_score: 4,  category: 'Equity defensivo — Utilities',      explanation: 'Sector eléctrico/agua/gas. Regulado, flujo de caja predecible, dividendos altos. Bajo beta. Sensible a tasas.',               source: 'Scoring base v1' },
  { identifier: 'CONSUMER_STAPLES_EQUITY',    identifier_type: 'category', name: 'Consumer Staples equity',                ticker: 'XLP',  asset_class: 'equity_defensive',   risk_score: 4,  category: 'Equity defensivo — Consumo básico', explanation: 'Empresas de consumo esencial (alimentación, bebidas, higiene). Resiliente en recesiones. Dividendos estables. Beta ~0.6.',      source: 'Scoring base v1' },
  { identifier: 'LOW_VOL_ETF',                identifier_type: 'category', name: 'Low volatility equity ETF',              ticker: 'SPLV', asset_class: 'equity_defensive',   risk_score: 4,  category: 'Equity baja volatilidad',           explanation: 'ETF que selecciona las acciones de menor volatilidad del S&P 500. Menor drawdown en caídas, menor retorno en alzas.',          source: 'Scoring base v1' },
  { identifier: 'COVERED_CALL_ETF',           identifier_type: 'category', name: 'Covered call / buy-write ETF',           ticker: 'XYLD', asset_class: 'equity_defensive',   risk_score: 4,  category: 'Equity income — Opciones cubiertas', explanation: 'ETF que vende opciones call sobre su cartera. Genera ingreso por prima, limita upside. Perfil income + baja vol relativa.',     source: 'Scoring base v1' },
  { identifier: 'GOLD_ETF',                   identifier_type: 'category', name: 'Gold ETF',                               ticker: 'GLD',  asset_class: 'equity_defensive',   risk_score: 4,  category: 'Commodity — Oro',                   explanation: 'Exposición al precio del oro físico. Activo refugio, cobertura inflación y eventos tail risk. Correlación baja con equity.',   source: 'Scoring base v1' },
  { identifier: 'REIT_DEFENSIVE',             identifier_type: 'category', name: 'REITs defensivos',                       ticker: 'VNQ',  asset_class: 'equity_defensive',   risk_score: 4,  category: 'Real estate defensivo',             explanation: 'REITs de sectores defensivos (salud, industrial, residencial). Flujo de caja estable, obligación de distribución del 90%.',    source: 'Scoring base v1' },
  { identifier: 'INFRASTRUCTURE_FUND',        identifier_type: 'category', name: 'Infrastructure equity fund',             ticker: 'IGF',  asset_class: 'equity_defensive',   risk_score: 4,  category: 'Infraestructura — Equity',          explanation: 'Acciones de empresas de infraestructura (peajes, aeropuertos, utilities). Flujos regulados, largo plazo, bajo ciclo.',        source: 'Scoring base v1' },
  { identifier: 'CONVERTIBLE_IG',             identifier_type: 'category', name: 'Convertible bonds investment grade',     ticker: 'CWB',  asset_class: 'fixed_income_ig',    risk_score: 4,  category: 'Bono convertible IG',               explanation: 'Bono con opción a convertir en acciones. Protección downside (bono) + potencial upside (equity). Emisores IG.',              source: 'Scoring base v1' },
  { identifier: 'BALANCED_CONSERVATIVE_PORT', identifier_type: 'category', name: 'Cartera balanceada conservadora',        ticker: null,   asset_class: 'equity_defensive',   risk_score: 4,  category: 'Multi-activo conservador',          explanation: 'Asignación típica 60% RF / 40% RV. Perfil mixto orientado a preservación con algo de crecimiento.',                           source: 'Scoring base v1' },
  { identifier: 'INCOME_FUND',                identifier_type: 'category', name: 'Income fund diversificado',              ticker: null,   asset_class: 'equity_defensive',   risk_score: 4,  category: 'Fondo income multi-activo',         explanation: 'Fondo orientado a generación de ingresos. Combina dividendos, bonos HY moderado, preferentes. Retorno estable.',              source: 'Scoring base v1' },
  { identifier: 'MULTI_ASSET_CONSERVATIVE',   identifier_type: 'category', name: 'Multi-asset conservative fund',          ticker: null,   asset_class: 'equity_defensive',   risk_score: 4,  category: 'Fondo multi-activo moderado-bajo',  explanation: 'Fondo con asignación dinámica entre clases de activo, sesgo conservador. Gestión activa de riesgo.',                        source: 'Scoring base v1' },

  // ── SCORE 5 — MODERADO ──────────────────────────────────────────────────────
  { identifier: 'SP500_ETF',                  identifier_type: 'category', name: 'S&P 500 ETF',                            ticker: 'SPY',  asset_class: 'equity_diversified', risk_score: 5,  category: 'Equity USA broad market',           explanation: 'ETF que replica el S&P 500. 500 empresas de mayor capitalización de EE.UU. Benchmark estándar renta variable global.',         source: 'Scoring base v1' },
  { identifier: 'MSCI_WORLD_ETF',             identifier_type: 'category', name: 'MSCI World ETF',                         ticker: 'URTH', asset_class: 'equity_diversified', risk_score: 5,  category: 'Equity mercados desarrollados',      explanation: 'ETF que replica el MSCI World (1600+ empresas de mercados desarrollados). Máxima diversificación geográfica en equity.',       source: 'Scoring base v1' },
  { identifier: 'DEVELOPED_MARKETS_EQUITY',   identifier_type: 'category', name: 'Developed markets equity ex-US',         ticker: 'EFA',  asset_class: 'equity_diversified', risk_score: 5,  category: 'Equity mercados desarrollados',      explanation: 'Acciones de mercados desarrollados excluyendo EE.UU. (Europa, Japón, Australasia). Diversificación regional.',               source: 'Scoring base v1' },
  { identifier: 'BROAD_MARKET_ETF',           identifier_type: 'category', name: 'Broad market US equity ETF',             ticker: 'VTI',  asset_class: 'equity_diversified', risk_score: 5,  category: 'Equity USA total market',           explanation: 'ETF de mercado total USA (large + mid + small caps). Mayor diversificación que S&P 500, incluye todo el mercado.',            source: 'Scoring base v1' },
  { identifier: 'GLOBAL_DIV_EQUITY_FUND',     identifier_type: 'category', name: 'Global diversified equity fund',         ticker: null,   asset_class: 'equity_diversified', risk_score: 5,  category: 'Fondo equity global diversificado',  explanation: 'Fondo de acciones globales diversificado geográfica y sectorialmente. Gestión activa o pasiva, benchmark MSCI ACWI.',        source: 'Scoring base v1' },
  { identifier: 'BALANCED_MODERATE',          identifier_type: 'category', name: 'Cartera balanceada moderada (60/40)',    ticker: null,   asset_class: 'equity_diversified', risk_score: 5,  category: 'Multi-activo moderado (60/40)',      explanation: 'Cartera clásica 60% renta variable / 40% renta fija. Benchmark de referencia para inversores moderados.',                   source: 'Scoring base v1' },
  { identifier: 'BLEND_EQUITY_FUND',          identifier_type: 'category', name: 'Blend equity fund (large cap)',          ticker: null,   asset_class: 'equity_diversified', risk_score: 5,  category: 'Equity blend large cap',            explanation: 'Fondo de acciones blend (mezcla value y growth) de gran capitalización. Exposición market-weight diversificada.',             source: 'Scoring base v1' },
  { identifier: 'LARGE_CAP_BLEND',            identifier_type: 'category', name: 'Large Cap Blend',                        ticker: 'IVV',  asset_class: 'equity_diversified', risk_score: 5,  category: 'Equity large cap blend',            explanation: 'Acciones de gran capitalización, estilo blend. Sector relativamente diversificado, menos concentrado que growth puro.',       source: 'Scoring base v1' },
  { identifier: 'CORE_ALLOCATION_FUND',       identifier_type: 'category', name: 'Core allocation fund',                   ticker: null,   asset_class: 'equity_diversified', risk_score: 5,  category: 'Fondo asignación núcleo',           explanation: 'Fondo de asignación táctica con posición core en equity y RF. Busca equilibrar riesgo-retorno de largo plazo.',              source: 'Scoring base v1' },
  { identifier: 'ESG_DIVERSIFIED_FUND',       identifier_type: 'category', name: 'ESG diversified equity fund',            ticker: 'ESGV', asset_class: 'equity_diversified', risk_score: 5,  category: 'Equity ESG diversificado',          explanation: 'Fondo de renta variable con criterios ESG. Perfil de riesgo similar a broad market, excluyendo sectores controversiales.',    source: 'Scoring base v1' },
  { identifier: 'CORPORATE_BBB',              identifier_type: 'category', name: 'Corporate bonds BBB',                    ticker: 'VCSH', asset_class: 'fixed_income_ig',    risk_score: 5,  category: 'Renta fija corporativa BBB',        explanation: 'Bonos corporativos con calificación BBB (grado de inversión mínimo). Mayor spread y riesgo crédito que A/AA.',               source: 'Scoring base v1' },
  { identifier: 'REIT_DIVERSIFIED',           identifier_type: 'category', name: 'REIT equity diversificado',              ticker: 'VNQ',  asset_class: 'real_estate',        risk_score: 5,  category: 'Real estate diversificado',         explanation: 'REIT con exposición diversificada (comercial, residencial, industrial, salud). Distribución regular, volatilidad media.',     source: 'Scoring base v1' },
  { identifier: 'EQUITY_INCOME_DIVERSIFIED',  identifier_type: 'category', name: 'Equity income diversificado',            ticker: 'DVY',  asset_class: 'equity_diversified', risk_score: 5,  category: 'Equity income diversificado',       explanation: 'Fondo o ETF que combina dividendos altos con diversificación sectorial amplia. Income + apreciación de capital.',            source: 'Scoring base v1' },

  // ── SCORE 6 — MODERADO ALTO ─────────────────────────────────────────────────
  { identifier: 'HIGH_YIELD_BONDS',           identifier_type: 'category', name: 'High Yield Bonds',                       ticker: 'HYG',  asset_class: 'fixed_income_hy',    risk_score: 6,  category: 'Renta fija high yield',             explanation: 'Bonos corporativos sub-investment grade (BB y menores). Mayor rendimiento, mayor riesgo de default, correlación con equity.',  source: 'Scoring base v1' },
  { identifier: 'SMALL_CAP_BLEND',            identifier_type: 'category', name: 'Small Cap Blend equity',                 ticker: 'IWM',  asset_class: 'equity_diversified', risk_score: 6,  category: 'Equity small caps',                 explanation: 'Acciones de pequeña capitalización (Russell 2000). Mayor crecimiento potencial pero mayor volatilidad y menor liquidez.',     source: 'Scoring base v1' },
  { identifier: 'MID_CAP_EQUITY',             identifier_type: 'category', name: 'Mid Cap equity',                         ticker: 'IJH',  asset_class: 'equity_diversified', risk_score: 6,  category: 'Equity mid caps',                   explanation: 'Acciones de capitalización media. Combinación de potencial crecimiento (small cap) y estabilidad (large cap).',              source: 'Scoring base v1' },
  { identifier: 'PREFERRED_HY',               identifier_type: 'category', name: 'Preferred shares high yield',            ticker: null,   asset_class: 'fixed_income_hy',    risk_score: 6,  category: 'Acciones preferentes HY',           explanation: 'Preferentes de emisores sub-investment grade. Alto dividendo, baja prioridad en quiebra, volatilidad elevada.',              source: 'Scoring base v1' },
  { identifier: 'FRONTIER_BONDS',             identifier_type: 'category', name: 'Frontier market bonds',                  ticker: null,   asset_class: 'fixed_income_hy',    risk_score: 6,  category: 'Renta fija frontier markets',       explanation: 'Bonos de países frontier (menor desarrollo que EM). Mayor rendimiento, mayor riesgo político/cambiario/liquidez.',           source: 'Scoring base v1' },
  { identifier: 'REIT_AGGRESSIVE',            identifier_type: 'category', name: 'REITs agresivos / especializados',       ticker: null,   asset_class: 'real_estate',        risk_score: 6,  category: 'Real estate agresivo',              explanation: 'REITs de sectores más volátiles (hoteles, oficinas, retail). Mayor exposición al ciclo económico.',                         source: 'Scoring base v1' },
  { identifier: 'SECTOR_DIVERSIFIED_FUND',    identifier_type: 'category', name: 'Sector diversified fund',                ticker: null,   asset_class: 'equity_diversified', risk_score: 6,  category: 'Fondo sectorial diversificado',      explanation: 'Fondo que combina varios sectores con overweight en segmentos cíclicos. Mayor beta que broad market.',                     source: 'Scoring base v1' },
  { identifier: 'MULTI_ASSET_AGGRESSIVE',     identifier_type: 'category', name: 'Multi-asset aggressive',                 ticker: null,   asset_class: 'equity_diversified', risk_score: 6,  category: 'Fondo multi-activo agresivo',       explanation: 'Asignación dinámica con sesgo agresivo: overweight equity, HY, EM. Mayor retorno esperado y mayor volatilidad.',           source: 'Scoring base v1' },
  { identifier: 'BANK_SUBORDINATED_DEBT',     identifier_type: 'category', name: 'Bank subordinated debt / AT1',           ticker: null,   asset_class: 'fixed_income_hy',    risk_score: 6,  category: 'Deuda subordinada bancaria',        explanation: 'Bonos subordinados y CoCos de bancos. Absorben pérdidas antes que deuda senior. Cupones altos, riesgo regulatorio.',        source: 'Scoring base v1' },
  { identifier: 'CLO_FUND',                   identifier_type: 'category', name: 'CLO / Loan fund',                        ticker: null,   asset_class: 'fixed_income_hy',    risk_score: 6,  category: 'CLO / Préstamos sindicados',        explanation: 'Obligaciones colateralizadas por préstamos corporativos. Estructura compleja, tasa flotante, riesgo crédito elevado.',       source: 'Scoring base v1' },
  { identifier: 'FLOATING_RATE_HY',           identifier_type: 'category', name: 'Floating rate high yield',               ticker: 'BKLN', asset_class: 'fixed_income_hy',    risk_score: 6,  category: 'Renta fija HY tasa flotante',       explanation: 'Préstamos bancarios sindicados de tasa flotante a emisores sub-IG. Protección tasa + riesgo crédito elevado.',              source: 'Scoring base v1' },
  { identifier: 'STRUCTURED_INCOME',          identifier_type: 'category', name: 'Structured income products',             ticker: null,   asset_class: 'fixed_income_hy',    risk_score: 6,  category: 'Productos estructurados income',    explanation: 'Notas estructuradas con capital protegido o condicionado. Perfil asimétrico. Riesgo emisor + riesgo estructura.',           source: 'Scoring base v1' },

  // ── SCORE 7 — AGRESIVO ──────────────────────────────────────────────────────
  { identifier: 'NASDAQ_100_QQQ',             identifier_type: 'category', name: 'Nasdaq 100 / QQQ',                       ticker: 'QQQ',  asset_class: 'equity_growth',      risk_score: 7,  category: 'Equity growth — Tecnología USA',    explanation: 'ETF que replica el Nasdaq 100. Alta concentración en tech. P/E elevado. Drawdowns de 35-80% registrados.',                  source: 'Scoring base v1' },
  { identifier: 'GROWTH_EQUITY_FUND',         identifier_type: 'category', name: 'Growth equity fund',                     ticker: 'IWF',  asset_class: 'equity_growth',      risk_score: 7,  category: 'Equity growth diversificado',       explanation: 'Fondo de acciones growth (alto crecimiento estimado). Mayor P/E, mayor sensibilidad a tasas y ciclo económico.',            source: 'Scoring base v1' },
  { identifier: 'TECHNOLOGY_FUND',            identifier_type: 'category', name: 'Technology sector fund',                 ticker: 'XLK',  asset_class: 'equity_growth',      risk_score: 7,  category: 'Equity — Tecnología',               explanation: 'Fondo sectorial tecnológico. Alto potencial de crecimiento, alta volatilidad, concentración en pocas posiciones grandes.',    source: 'Scoring base v1' },
  { identifier: 'BIOTECH_FUND',               identifier_type: 'category', name: 'Biotech / Healthcare growth fund',       ticker: 'XBI',  asset_class: 'equity_growth',      risk_score: 7,  category: 'Equity — Biotech',                  explanation: 'Sector biotecnológico. Altos retornos potenciales por aprobaciones FDA. Riesgo binario muy elevado por ensayos clínicos.',   source: 'Scoring base v1' },
  { identifier: 'COMMODITIES_BROAD',          identifier_type: 'category', name: 'Commodities broad basket',               ticker: 'DJP',  asset_class: 'commodity',          risk_score: 7,  category: 'Commodities diversificados',        explanation: 'Exposición a cesta diversificada de materias primas (energía, metales, agrícolas). Alta volatilidad, cobertura inflación.',  source: 'Scoring base v1' },
  { identifier: 'EMERGING_MARKETS_DEBT',      identifier_type: 'category', name: 'Emerging Markets Debt (EM Bonds)',       ticker: 'EMB',  asset_class: 'fixed_income_hy',    risk_score: 7,  category: 'Renta fija mercados emergentes',     explanation: 'Bonos soberanos y corporativos de mercados emergentes en USD. Mayor spread, riesgo político, cambiario y liquidez.',         source: 'Scoring base v1' },
  { identifier: 'CHINA_EQUITY_FUND',          identifier_type: 'category', name: 'China equity fund',                      ticker: 'MCHI', asset_class: 'equity_emerging',    risk_score: 7,  category: 'Equity China',                      explanation: 'Acciones chinas (A-shares, H-shares, ADRs). Riesgo regulatorio específico China, geopolítico, opacidad contable.',          source: 'Scoring base v1' },
  { identifier: 'LATAM_EQUITY',               identifier_type: 'category', name: 'Latin America equity',                   ticker: 'ILF',  asset_class: 'equity_emerging',    risk_score: 7,  category: 'Equity América Latina',             explanation: 'Acciones de mercados latinoamericanos (Brasil, México, Chile). Alta sensibilidad a commodities y tipo de cambio.',          source: 'Scoring base v1' },
  { identifier: 'LEVERAGED_BOND',             identifier_type: 'category', name: 'Leveraged bond fund',                    ticker: null,   asset_class: 'fixed_income_hy',    risk_score: 7,  category: 'Renta fija apalancada',             explanation: 'Fondo de bonos con uso de apalancamiento para ampliar retornos. Mayor riesgo en caídas, posibles margin calls.',             source: 'Scoring base v1' },
  { identifier: 'CONCENTRATED_SECTOR_ETF',    identifier_type: 'category', name: 'Concentrated sector ETF',                ticker: null,   asset_class: 'equity_growth',      risk_score: 7,  category: 'Equity sectorial concentrado',       explanation: 'ETF con foco en un sector específico (semiconductores, finanzas, energía). Alta concentración, sin diversificación.',        source: 'Scoring base v1' },
  { identifier: 'MOMENTUM_FUND',              identifier_type: 'category', name: 'Momentum equity fund',                   ticker: 'MTUM', asset_class: 'equity_growth',      risk_score: 7,  category: 'Equity factor — Momentum',          explanation: 'Fondo que sobrepondera acciones con mejor rendimiento reciente. Factor momentum amplifica ciclos, alta rotación.',           source: 'Scoring base v1' },
  { identifier: 'INNOVATION_FUND',            identifier_type: 'category', name: 'Innovation / Disruptive fund',           ticker: 'ARKK', asset_class: 'equity_growth',      risk_score: 7,  category: 'Equity temático innovación',        explanation: 'Fondo de empresas disruptivas (genómica, fintech, robótica). Alta concentración, alto P/E, drawdowns históricos >50%.',     source: 'Scoring base v1' },
  { identifier: 'CYBERSECURITY_FUND',         identifier_type: 'category', name: 'Cybersecurity thematic fund',            ticker: 'CIBR', asset_class: 'equity_growth',      risk_score: 7,  category: 'Equity temático — Ciberseguridad',  explanation: 'Empresas de ciberseguridad. Sector creciente, concentrado en pocas posiciones, alta volatilidad sectorial.',                source: 'Scoring base v1' },
  { identifier: 'AI_THEMATIC_FUND',           identifier_type: 'category', name: 'AI / Artificial Intelligence fund',      ticker: null,   asset_class: 'equity_growth',      risk_score: 7,  category: 'Equity temático — Inteligencia Artificial', explanation: 'Fondo temático de inteligencia artificial. Alta expectativa de crecimiento, valoraciones elevadas, concentración tech.', source: 'Scoring base v1' },

  // ── SCORE 8 — MUY AGRESIVO ──────────────────────────────────────────────────
  { identifier: 'EM_EQUITY',                  identifier_type: 'category', name: 'Emerging Markets equity broad',          ticker: 'EEM',  asset_class: 'equity_emerging',    risk_score: 8,  category: 'Equity mercados emergentes',        explanation: 'Acciones de mercados emergentes amplios (China, India, Brasil, Taiwán, Corea). Mayor potencial, mayor volatilidad que DM.',   source: 'Scoring base v1' },
  { identifier: 'SINGLE_STOCK_LARGE_GROWTH',  identifier_type: 'category', name: 'Single stock large cap growth',          ticker: null,   asset_class: 'equity_growth',      risk_score: 8,  category: 'Acción individual — Large cap growth', explanation: 'Posición en una sola acción de alta capitalización growth. Sin diversificación, riesgo idiosincrático elevado.',            source: 'Scoring base v1' },
  { identifier: 'SINGLE_STOCK_CYCLICAL',      identifier_type: 'category', name: 'Single stock cíclico',                   ticker: null,   asset_class: 'equity_growth',      risk_score: 8,  category: 'Acción individual — Cíclico',       explanation: 'Posición concentrada en una acción cíclica (energía, materiales). Alta volatilidad ligada al ciclo económico.',            source: 'Scoring base v1' },
  { identifier: 'FRONTIER_MARKETS_EQUITY',    identifier_type: 'category', name: 'Frontier Markets equity',                ticker: 'FM',   asset_class: 'equity_emerging',    risk_score: 8,  category: 'Equity frontier markets',           explanation: 'Acciones de mercados frontera (Vietnam, Nigeria, Kazajistán). Menor liquidez, mayor riesgo país, alta volatilidad.',         source: 'Scoring base v1' },
  { identifier: 'COMMODITY_PRODUCERS',        identifier_type: 'category', name: 'Commodity producers equity',             ticker: 'XME',  asset_class: 'equity_emerging',    risk_score: 8,  category: 'Equity productores de commodities',  explanation: 'Acciones de empresas productoras de materias primas. Apalancamiento operativo sobre precio commodity, alta volatilidad.',   source: 'Scoring base v1' },
  { identifier: 'OIL_GAS_EXPLORATION',        identifier_type: 'category', name: 'Oil & Gas exploration equity',           ticker: 'XOP',  asset_class: 'equity_growth',      risk_score: 8,  category: 'Equity — Exploración O&G',          explanation: 'Empresas de exploración petróleo y gas. Riesgo geológico + precio commodity + geopolítico. Drawdowns >50% frecuentes.',    source: 'Scoring base v1' },
  { identifier: 'JUNIOR_MINERS',              identifier_type: 'category', name: 'Junior miners equity',                   ticker: null,   asset_class: 'equity_emerging',    risk_score: 8,  category: 'Equity — Minería junior',           explanation: 'Pequeñas empresas mineras en fase exploración/desarrollo. Riesgo extremo de proyecto, baja liquidez, alta volatilidad.',    source: 'Scoring base v1' },
  { identifier: 'VENTURE_GROWTH_FUND',        identifier_type: 'category', name: 'Venture / growth equity fund',           ticker: null,   asset_class: 'equity_growth',      risk_score: 8,  category: 'Private equity — Venture growth',   explanation: 'Fondo de equity en empresas de crecimiento tardío pre-IPO. Iliquidez, valoraciones agresivas, horizonte 5-10 años.',         source: 'Scoring base v1' },
  { identifier: 'PE_GROWTH',                  identifier_type: 'category', name: 'Private equity growth',                  ticker: null,   asset_class: 'equity_growth',      risk_score: 8,  category: 'Private equity growth',             explanation: 'Inversión en private equity crecimiento. Ilíquido, largo plazo, high fees. Retornos potenciales altos si el exit es exitoso.', source: 'Scoring base v1' },
  { identifier: 'CONCENTRATED_ACTIVE_EQUITY', identifier_type: 'category', name: 'Concentrated active equity fund',        ticker: null,   asset_class: 'equity_growth',      risk_score: 8,  category: 'Fondo equity concentrado activo',   explanation: 'Fondo de gestión activa con 10-20 posiciones. Tracking error muy alto, riesgo gestor, potencial alpha o pérdida.',           source: 'Scoring base v1' },
  { identifier: 'LEVERAGED_COMMODITIES',      identifier_type: 'category', name: 'Leveraged commodity fund',               ticker: null,   asset_class: 'commodity',          risk_score: 8,  category: 'Commodities apalancados',           explanation: 'Exposición apalancada a materias primas. Amplificación volatilidad, decay por roll de futuros en mercados contango.',        source: 'Scoring base v1' },
  { identifier: 'HIGH_BETA_EQUITY',           identifier_type: 'category', name: 'High beta equity',                       ticker: null,   asset_class: 'equity_growth',      risk_score: 8,  category: 'Equity alto beta',                  explanation: 'Acciones con beta >1.5 respecto al mercado. Amplifican tanto subidas como caídas del mercado.',                            source: 'Scoring base v1' },
  { identifier: 'SPECULATIVE_THEMATIC',       identifier_type: 'category', name: 'Speculative thematic fund',              ticker: null,   asset_class: 'equity_growth',      risk_score: 8,  category: 'Fondo temático especulativo',       explanation: 'Fondo temático en sectores especulativos (cannabis, NFTs, metaverso). Narrativa fuerte, fundamentales débiles.',             source: 'Scoring base v1' },

  // ── SCORE 9 — ESPECULATIVO ──────────────────────────────────────────────────
  { identifier: 'BITCOIN',                    identifier_type: 'category', name: 'Bitcoin',                                ticker: 'BTC',  asset_class: 'crypto',             risk_score: 9,  category: 'Crypto — Bitcoin',                  explanation: 'Criptomoneda de mayor capitalización. Volatilidad anualizada >60%. Drawdowns de 80%+ registrados. Sin flujo de caja subyacente.', source: 'Scoring base v1' },
  { identifier: 'ETHEREUM',                   identifier_type: 'category', name: 'Ethereum',                               ticker: 'ETH',  asset_class: 'crypto',             risk_score: 9,  category: 'Crypto — Ethereum',                 explanation: 'Segunda criptomoneda por capitalización. Plataforma de contratos inteligentes. Alta volatilidad, correlación con BTC.',        source: 'Scoring base v1' },
  { identifier: 'DISTRESSED_DEBT',            identifier_type: 'category', name: 'Distressed debt',                        ticker: null,   asset_class: 'fixed_income_hy',    risk_score: 9,  category: 'Deuda distressed',                  explanation: 'Bonos de empresas en dificultades financieras o en default. Requiere expertise legal. Retornos potenciales muy altos o cero.', source: 'Scoring base v1' },
  { identifier: 'LEVERAGED_STRUCTURED',       identifier_type: 'category', name: 'Leveraged structured products',          ticker: null,   asset_class: 'other',              risk_score: 9,  category: 'Productos estructurados apalancados', explanation: 'Notas y certificados con apalancamiento incorporado. Pérdida de capital posible, riesgo emisor elevado.',                   source: 'Scoring base v1' },
  { identifier: 'NON_IG_DISTRESSED',          identifier_type: 'category', name: 'Non-IG distressed bonds CCC',            ticker: null,   asset_class: 'fixed_income_hy',    risk_score: 9,  category: 'Bonos CCC / CC / distressed',       explanation: 'Bonos corporativos con calificación CCC o inferior. Alta tasa de default esperada, recuperación incierta.',                source: 'Scoring base v1' },
  { identifier: 'VOLATILITY_TRADING',         identifier_type: 'category', name: 'Volatility trading products (VIX ETPs)', ticker: 'VXX',  asset_class: 'other',              risk_score: 9,  category: 'Trading de volatilidad',            explanation: 'ETPs que replican VIX o estrategias de volatilidad. Decay estructural severo, solo para trading de corto plazo.',             source: 'Scoring base v1' },
  { identifier: 'HEDGE_FUND_SPECULATIVE',     identifier_type: 'category', name: 'Hedge fund estrategias especulativas',   ticker: null,   asset_class: 'other',              risk_score: 9,  category: 'Hedge fund especulativo',           explanation: 'Fondos de cobertura con estrategias de alta convicción (long/short concentrado, event-driven, macro). Alta varianza.',        source: 'Scoring base v1' },
  { identifier: 'LEVERAGED_DERIVATIVES',      identifier_type: 'category', name: 'Leveraged derivatives / opciones',       ticker: null,   asset_class: 'other',              risk_score: 9,  category: 'Derivados apalancados',             explanation: 'Opciones, futuros y otros derivados con apalancamiento implícito. Puede perder el 100% del capital en posiciones largas.', source: 'Scoring base v1' },
  { identifier: 'CONCENTRATED_CRYPTO',        identifier_type: 'category', name: 'Concentrated crypto portfolio',          ticker: null,   asset_class: 'crypto',             risk_score: 9,  category: 'Crypto concentrado (2-5 monedas)',  explanation: 'Cartera de pocas criptomonedas seleccionadas. Mayor concentración que BTC/ETH solos, volatilidad extrema.',                 source: 'Scoring base v1' },
  { identifier: 'SPAC_SPECULATIVE',           identifier_type: 'category', name: 'SPAC especulativo',                      ticker: null,   asset_class: 'other',              risk_score: 9,  category: 'SPAC especulativo',                 explanation: 'Special Purpose Acquisition Company. Caja sin activo real hasta el deal. Post-merger altamente especulativo y volátil.',     source: 'Scoring base v1' },
  { identifier: 'DEEP_TECH_VENTURE',          identifier_type: 'category', name: 'Deep tech venture fund',                 ticker: null,   asset_class: 'other',              risk_score: 9,  category: 'Venture — Deep tech',               explanation: 'Fondo de capital riesgo en tecnología profunda (quantum, biotech early stage). Ilíquido, horizonte 10+ años, alto riesgo.', source: 'Scoring base v1' },

  // ── SCORE 10 — MÁXIMO RIESGO ────────────────────────────────────────────────
  { identifier: 'ALTCOINS_SPECULATIVE',        identifier_type: 'category', name: 'Altcoins especulativas (meme coins)',   ticker: null,   asset_class: 'crypto',             risk_score: 10, category: 'Crypto — Altcoins especulativas',   explanation: 'Criptomonedas de baja capitalización con narrativa especulativa. Pérdida total frecuente, manipulación de mercado, liquidez mínima.', source: 'Scoring base v1' },
  { identifier: 'PENNY_STOCKS',               identifier_type: 'category', name: 'Penny stocks',                           ticker: null,   asset_class: 'other',              risk_score: 10, category: 'Acciones especulativas — Penny',    explanation: 'Acciones de precio muy bajo (<$1), baja capitalización y escasa liquidez. Manipuladas frecuentemente. Riesgo de pérdida total.', source: 'Scoring base v1' },
  { identifier: 'MICROCAPS_ILLIQUID',         identifier_type: 'category', name: 'Microcaps ilíquidas',                    ticker: null,   asset_class: 'other',              risk_score: 10, category: 'Equity microcap ilíquido',          explanation: 'Acciones de empresas muy pequeñas con volumen de trading mínimo. Imposible salir en mercado adverso. Spread bid/ask enorme.', source: 'Scoring base v1' },
  { identifier: 'INVERSE_ETF',                identifier_type: 'category', name: 'Inverse ETF (short market)',             ticker: 'SH',   asset_class: 'other',              risk_score: 10, category: 'ETF inverso',                       explanation: 'ETF que replica el inverso del índice. Decay estructural por rebalanceo diario. Pierde valor en mercados laterales o alcistas.', source: 'Scoring base v1' },
  { identifier: 'LEVERAGED_ETF_2X_3X',        identifier_type: 'category', name: 'Leveraged ETF 2x / 3x',                 ticker: 'TQQQ', asset_class: 'other',              risk_score: 10, category: 'ETF apalancado 2x/3x',             explanation: 'ETF que amplifica 2x o 3x la rentabilidad diaria del índice. Decay diario destruye valor en largo plazo. Solo day trading.', source: 'Scoring base v1' },
  { identifier: 'NAKED_OPTIONS',              identifier_type: 'category', name: 'Naked options / opciones desnudas',      ticker: null,   asset_class: 'other',              risk_score: 10, category: 'Opciones no cubiertas',             explanation: 'Venta de opciones sin cobertura del activo subyacente. Pérdida potencial ilimitada en calls, muy alta en puts.',              source: 'Scoring base v1' },
  { identifier: 'HIGHLY_LEVERAGED_DERIV',     identifier_type: 'category', name: 'Derivados altamente apalancados',        ticker: null,   asset_class: 'other',              risk_score: 10, category: 'Derivados máximo apalancamiento',   explanation: 'CFDs, futuros con máximo apalancamiento. Margin calls pueden exceder capital inicial. Riesgo pérdida superior al 100%.',    source: 'Scoring base v1' },
  { identifier: 'MEME_STOCKS',                identifier_type: 'category', name: 'Meme stocks especulativas',              ticker: null,   asset_class: 'other',              risk_score: 10, category: 'Meme stocks',                       explanation: 'Acciones impulsadas por redes sociales sin fundamentales. GameStop, AMC style. Volatilidad extrema, pump & dump patterns.',    source: 'Scoring base v1' },
  { identifier: 'ILLIQUID_PRIVATE',           identifier_type: 'category', name: 'Illiquid private investments',           ticker: null,   asset_class: 'other',              risk_score: 10, category: 'Inversión privada ilíquida',        explanation: 'Inversiones privadas sin mercado secundario. Sin precio de salida, lock-up permanente, riesgo total de pérdida de capital.',   source: 'Scoring base v1' },
  { identifier: 'DISTRESSED_MICROCAP_DEBT',   identifier_type: 'category', name: 'Distressed microcap debt',               ticker: null,   asset_class: 'other',              risk_score: 10, category: 'Deuda distressed microcap',         explanation: 'Deuda de empresas micro con alto riesgo de quiebra. Prácticamente sin liquidez. Recuperación en default cercana a cero.',    source: 'Scoring base v1' },
  { identifier: 'EXOTIC_STRUCTURED',          identifier_type: 'category', name: 'Exotic structured products',             ticker: null,   asset_class: 'other',              risk_score: 10, category: 'Productos estructurados exóticos',  explanation: 'Notas con payoffs complejos vinculados a eventos poco probables. Opacidad total. Riesgo de pérdida completa del capital.',   source: 'Scoring base v1' },
  { identifier: 'BINARY_OPTIONS',             identifier_type: 'category', name: 'Binary options',                         ticker: null,   asset_class: 'other',              risk_score: 10, category: 'Opciones binarias',                 explanation: 'Instrumentos tipo "todo o nada". Extremadamente especulativo. Regulado como apuesta en muchas jurisdicciones.',             source: 'Scoring base v1' },
]

export async function POST() {
  try {
    const session = await getSession()
    if (!session) return NextResponse.json({ error: 'No autorizado' }, { status: 401 })
    if (session.role !== 'admin') return NextResponse.json({ error: 'Solo admins pueden cargar el scoring base' }, { status: 403 })

    const rows = SEED_DATA.map(d => ({
      ...d,
      needs_review: false,
      updated_at: new Date().toISOString(),
    }))

    // Batch insert in groups of 20
    let inserted = 0
    let skipped  = 0
    for (let i = 0; i < rows.length; i += 20) {
      const batch = rows.slice(i, i + 20)
      const { data, error } = await supabaseAdmin
        .from('asset_master')
        .upsert(batch, { onConflict: 'identifier', ignoreDuplicates: true })
        .select('id')

      if (error) throw error
      inserted += data?.length ?? 0
      skipped  += batch.length - (data?.length ?? 0)
    }

    return NextResponse.json({
      ok: true,
      total:    rows.length,
      inserted,
      skipped,
      message: `${inserted} activos cargados, ${skipped} ya existían (no modificados).`,
    })
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
